### ISSUE TITLE
ImportError: cannot import name 'stable_diffusion_3_guidance' from 'threestudio-dreambeast.guidance'

### ISSUE THREAD

**Issue by lzt02** [runjiali-rl/threestudio-dreambeast#3]
Excellent work! I encountered an error while running the code: 

```
File "custom/threestudio-dreambeast/__init__.py", line 17, in <module>
    from .guidance import mvdream_guidance, stable_diffusion_3_guidance, stable_diffusion_3_prompt_processor
ImportError: cannot import name 'stable_diffusion_3_guidance' from 'threestudio-dreambeast.guidance' (unknown location)
```

I found that there is only `mvdream_guidance. py` in the `guidance/`, and there are no `stable-diffusion_3_guidance` and `stable-diffusion_3_comptsprocessor`

Thanks in advance for your help.

**Comment by runjiali-rl** [comment]
Hi,

Thank you so much for letting me know. I have fixed the bug. Hopefully it will work on your side
